import express from 'express'; import cors from 'cors'; import fs from 'node:fs/promises'; import path from 'node:path'; import crypto from 'node:crypto'; import {spawn} from 'node:child_process';
const root=path.resolve('data'); await fs.mkdir(root,{recursive:true}); const history=path.join(root,'history.json');
async function readHistory(){try{return JSON.parse(await fs.readFile(history,'utf8'))}catch{return []}} async function writeHistory(x){await fs.writeFile(history,JSON.stringify(x,null,2))}
function run(command,args,{input='',cwd=process.cwd()}={}){return new Promise((resolve,reject)=>{const p=spawn(command,args,{cwd,shell:true,windowsHide:true});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',c=>c?reject(new Error(err||out)):resolve(out)) ; if(input)p.stdin.end(input);})}
const app=express(); app.use(cors()); app.use(express.json({limit:'10mb'})); const jobs=new Map();
app.get('/api/repos',async(_q,res)=>{try{const out=await run('gh',['repo','list','--limit','100','--json','nameWithOwner,description']);res.json({repos:JSON.parse(out)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/jobs',async(req,res)=>{const id=crypto.randomUUID(), job={id,status:'queued',createdAt:new Date().toISOString(),repo:req.body.repo,messages:req.body.messages||[]};jobs.set(id,job); const dir=path.join(root,'jobs',id); await fs.mkdir(dir,{recursive:true}); await fs.writeFile(path.join(dir,'messages.json'),JSON.stringify(job.messages,null,2)); runJob(job,dir); res.status(202).json({id,status:job.status})});
app.get('/api/jobs/:id',(req,res)=>{const job=jobs.get(req.params.id); job?res.json({job}):res.status(404).json({error:'Not found'})}); app.get('/api/history',async(_q,res)=>res.json({history:await readHistory()}));
async function runJob(job,dir){job.status='processing';try{const prompt=`You are triaging WhatsApp support messages into one GitHub issue. Repository: ${job.repo}. Read ${path.join(dir,'messages.json')}. Produce ONLY valid JSON with keys title, body, labels (array). Infer the affected product/school/module when present. Include a concise reproduction summary, expected behavior, actual behavior, evidence/media references, and open questions. Do not invent facts.`; const raw=await run('gemini',['-p',JSON.stringify(prompt)]); const match=raw.match(/\{[\s\S]*\}/); if(!match)throw new Error('Gemini did not return JSON'); const issue=JSON.parse(match[0]); const out=await run('gh',['issue','create','--repo',job.repo,'--title',JSON.stringify(issue.title),'--body',JSON.stringify(issue.body)]); const url=out.trim().split(/\s+/).find(x=>x.includes('/issues/'))||out.trim(); Object.assign(job,{status:'completed',issueUrl:url,issue,completedAt:new Date().toISOString()})}catch(e){Object.assign(job,{status:'failed',error:e.message})} const h=await readHistory(); h.unshift(job); await writeHistory(h)}
app.listen(8765,'127.0.0.1',()=>console.log('WhatsApp Issue Bridge listening on http://127.0.0.1:8765'));
